// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';
define(["exports"],
  function(exports){
    'use strict';
    var x = "a";
    
    exports.x = x;
    
  })
/* No side effect */
